version: "3.8"

services:
  telegram-bot:
    build: .
    container_name: telegram-bot
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
    # Uncomment if using webhooks:
    # ports:
    #   - "8443:8443"

  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    env_file:
      - .env.postgres
    ports:
      - "5433:5432"  # Exposes container port 5432 on host port 5433
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-shedipes95} -d ${POSTGRES_DB:-telegram_bot}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
